auto: true

markdown: redcarpet
redcarpet:
    extensions: ["tables"]
pygments: true
paginate: 8
permalink: /:title

title: Burning
url: http://www.dechao.net
feed: /atom.xml
author_info: <a href="http://www.dechao.net/">Burning</a>
