auto: true

markdown: redcarpet
redcarpet: 
    extensions: ["tables"]
pygments: true
paginate: 8
permalink: /:title

title: Warning
url: http://dechao.com
feed: /atom.xml
author_info: <a href="http://dechao.com/">Warning</a>
